[package]
name = "enums_and_match"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "compare_numbers"
path = "src/compare_numbers.rs"

[dependencies]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
